GOOGLE_API_KEYS = "AIzaSyC19t0uge5u5XmagsDajHfWveWddu6BQTA,AIzaSyBiMJFSOrPDki8VujfXNn4h2w_nphVNo8Y,AIzaSyCq8Qxnu2zQvJ9T2f1smanUS9w1s02YXsw,AIzaSyATT7HYuqyGyGXjPC8tkg-OoZMVB4K6dXw,AIzaSyBzc2SD3-k8IDcaFBpUoEik11i2iW6YD7o"

GDRIVE_FOLDER_ID = "1rBVZ0mwDQNj7_1_CdMNfdL7kI1wt2-Ve"

[GDRIVE_CREDENTIALS]
type = "service_account"
project_id = "fast-memory-a41e6"
private_key_id = "a06c102828a95f1ff782df10955e6eaaa19328e9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCo7DdlSenC6UDB
424c26m1YUBoduG3Cw7nK3o8r9Q1YiTGD9NeN4phKuGCOpmXx6IZqASdEurVuQVV
UUkSTejEaqyWlrT9ie24L5HwdLiDSP4picJ5enBh4T8yb3PJSDTAS2QQJ3Ax1m4d
FH4iVVTJReY/tZ3cCnIpDPLgfX5+U4qYKIl/UUSqxDwSRlJAPEDaarWET+Gqdi3W
W5EOcSw6docfjTCES5kfFHH8AKR7+H1KsoASqffM1svKwbIf7B3cBJAXRc5C+o3a
lctdOK5ZSrH1araynOMmsoXlyF3S3U/w8st6Q68Hh9ZxC/pwHyjnY0VbYNmy+T9P
JQhMmiJ1AgMBAAECggEAEPIleoFINJfuuaSlorp8k2gOrIwkh5bR52nqqNTgvnw6
gS4MP7rlpGrHVaeoSdwqjFVZJSLFMSyO9uihIndzXuTurGqw/HBOSzhmdQ9YhT8Y
1DTwL/yS8pbEnrwkivA17oaBosc6D53ZzQwFvU7/IvPirch77huUKT8VzGR6gJSa
H98UmIJes38OgGH0/BJH+agIaKOBBlxNvzcwkp4+giNfiwoyud+mM1oWhNmSEo/x
SK1WSOaNvi2cLyDTdonQwqrg7b+j9XdNf5tI+Q96XNO0lvKmHZHIUDsEbYSJ5gFh
+QeEBFArKo0fS6dfVgNIhJnbhxQd0yMJPmmQUw1L0QKBgQDakRAJsBXOdddV1ti+
5Adxcnl1ZXa40lGf2QXlxnN7tugqLK1EO0C9A5Lylrbos2OMVV8CiGI70W2HKinY
JQIW9wcMOMCkKpsWiEPgpYFsa6l8eHJPsQk5/x0dWSA31Hth3/LPoje3dfmHb9yW
Zi1spnWFM7emZQuzBltsK+ZtuQKBgQDF2orSzZQnsVy69F4BZhYWBeozOakkaR3p
VpB0Z7afRM/FvDImfs03sLnJuziuex0JYy+XOu4hswzQfAeZ1aOsWBYoyZuLv5VW
sd0UT039o1UvY2rg6d4JmrYcRJVTMwkhx6j5ar1Z9Qg2A9OOHb1hsAZL1ETXNJWh
QS6+MbuYnQKBgQCZlKNDW3MHP3DPhYeKIytDwV+taV2SI19txg7J1bfiL7VVpU0f
C8/CwVcplVPzkdIakwaO/gyg4dlnx+3dTqv4PR67rMlY0gNmQtwHZ+TYrZJLv0r7
ynekRCpOLAlikbEdJkM1OVSTWpe7XpQPLr8ugI1FywB6MLiW1Jm7GeHyKQKBgE0P
3/5XYBtNs6aFw4+b6YJOb3fgP4cVAjd+JemQ88p5DMwhjw77WIcWaGawa1VaUmbz
oPewVkv950HU7Uj3szZPYOImFFWMG2iXAlsEwIXH9kfs2xYbQQZQohnEhLzRJf9o
OuJatsGw9K/FMcMqxjakTu9+EAoaSyVxs/kUedLpAoGADYmmuix9Ug6hYuqkN7nZ
r4PUE7qWkDAyyEKjcbfzhye0Zvgl7WCPOEUASaef2ZFey8pzGy7g38TofAMdcQTQ
wcxaM3J+ndXk/7e+CLX4UT+AonwtUsU8ZrKG+DnWxfzDZE1EOBMJn9EcBOrnwV5U
JnZD23b33XNzmpO97LWqaxU=
-----END PRIVATE KEY-----
"""
client_email = "aws-cache@fast-memory-a41e6.iam.gserviceaccount.com"
client_id = "107421578887018178261"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/aws-cache%40fast-memory-a41e6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
